### ISSUE TITLE
Startseite für die Pizza Website

### ISSUE THREAD

**Issue by salnhan** [tsunami010904/pizza_fantastico.github.io#1]
Als Besucher möchte ich eine Startseite der Pizza Website ansehen

Die Seite besteht aus:
* Ein Navigation
* Ein Slider/Karussell mit 3 Bilder
* 3 Spalten mit Text und Thumbnail unter dem Slider 

siehe https://getbootstrap.com/docs/5.0/examples/carousel/

**Comment by tsunami010904** [comment]
In Bearbeitung von Minh Thai.
Fortschritt: ca. 40 %

**Comment by tsunami010904** [comment]
Ich mache das gerade

**Comment by tsunami010904** [comment]
Mache ich gerade

**Comment by tsunami010904** [comment]
To Do:

- richtig verlinken
- Footer verbessern (+Öffnungszeiten)
- About us einfügen
- Slider + 3 Spalten verbessern

**Comment by tsunami010904** [comment]
Mache ich gerade

**Comment by tsunami010904** [comment]
Mache ich gerade
